export default function About({ onBack }) {
  return (
    <div className="about-page">
      <nav className="navbar">
        <a className="logo" href="#" onClick={(e) => { e.preventDefault(); onBack(); }}>
          VERSUS<span> ARENA</span>
        </a>
        <ul className="nav-links">
          <li><a href="#" className="nav-back-link" onClick={(e) => { e.preventDefault(); onBack(); }}>Back to the Arena</a></li>
        </ul>
      </nav>

      <div className="about-container">
        <div className="about-tag">My Mission</div>
        <h1 className="about-title">Why <span className="vs-word">Versus Arena</span></h1>

        <div className="about-section">
          <p className="about-lead">
            I've always been passionate about battles across verses, but things like the
            internet, online debaters, and wikis tend to be biased toward their favorite character.
            I'm here to break that pattern.
          </p>
          <p>
            Versus Arena is built to be a reliable, non-biased home for anyone who shares this
            passion. Whether you're making a YouTube video, settling an online debate,
            or just curious because something sparked your interest, you can come here and
            put any character against any other.
          </p>
        </div>

        <div className="about-divider" />

        <div className="about-section">
          <h2 className="about-subtitle">How It Works</h2>
          <p>
            Some characters are too niche, lack a proper wiki, or have very little public backstory.
            When that happens, the search may not find them, and that's where you come in.
          </p>
          <p>
            Every battle has a <strong>Custom Feats / Lore</strong> field where you can manually
            add what we don't know about a character. Their canonical strength feats, unique
            powers, lore details, or anything else relevant. Each addition is logged in the final
            verdict, so anyone reading can see exactly which information shaped the outcome:
            complete transparency, no hidden inputs.
          </p>
          <p>
            I'm also building tools to help you reason about feats yourself:
            speed-vs-mass calculators, durability scaling helpers, and more, so you can
            quantify the matchup with confidence rather than vibes.
          </p>
        </div>

        <div className="about-divider" />

        <div className="about-section">
          <h2 className="about-subtitle">The Verdict System</h2>
          <p>
            Every verdict is generated by analyzing canonical feats, power scaling, and lore.
            Both fighters are weighed against the same standardized criteria,
            with no thumb on the scale for the more popular character.
          </p>
          <p>
            If a battle is genuinely too close to call, the verdict says so.
            Honesty beats false confidence every time.
          </p>
        </div>

        <div className="about-divider" />

        <div className="about-section about-footer-cta">
          <p className="about-quiet">
            Found a bug? Have a character that won't load? Have ideas for new features?
            We're listening.
          </p>
          <button className="fight-btn about-cta-btn" onClick={onBack}>
            Enter the Arena
          </button>
        </div>
      </div>
    </div>
  );
}